before:
    hooks:
        - "go mod tidy"

builds:
    -   env:
            - "CGO_ENABLED=0"
        mod_timestamp: "{{ .CommitTimestamp }}"
        flags:
            - "-trimpath"
        goos:
            - "linux"
            - "darwin"
        goarch:
            - "amd64"
            - "arm64"
        main: "./main.go"

archives:
    -   format: "binary"
        name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

release:
    draft: true

changelog:
    skip: true
