before:
    hooks:
        - "go mod tidy"

builds:
    -   env:
            # Build a statically-linked binary without external dependencies.
            - "CGO_ENABLED=0"
        mod_timestamp: "{{ .CommitTimestamp }}"
        flags:
            # Remove all file system paths from the resulting executable.
            - "-trimpath"
        ldflags:
            # Omit the symbol table and debug information.
            - "-s"
            # Omit the DWARF symbol table.
            - "-w"
            # Populate build information into version variables.
            - "-X github.com/dbtedman/scrutinise/infrastructure/cmd.version={{.Version}}"
            - "-X github.com/dbtedman/scrutinise/infrastructure/cmd.commit={{.Commit}}"
            - "-X github.com/dbtedman/scrutinise/infrastructure/cmd.date={{.CommitDate}}"
        goos:
            - "linux"
            - "darwin"
            - "windows"
        goarch:
            - "amd64"
            - "arm64"
        main: "./main.go"

archives:
    -   format: "binary"
        id: "binary"
        name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    -   format: "zip"
        id: "zip"
        name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

checksum:
    name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
    algorithm: "sha256"

brews:
    -   name: "scrutinise"
        ids:
            - "binary"
        tap:
            owner: "dbtedman"
            name: "homebrew-tap"
            branch: "main"
            token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
        homepage: "https://github.com/dbtedman/scrutinise"
        description: "Tool to scrutinise website development security."
        license: "MIT"
        folder: "Formula"

scoops:
    -   name: "scrutinise"
        ids:
            - "zip"
        bucket:
            owner: "dbtedman"
            name: "scoop-bucket"
            branch: "main"
            token: "{{ .Env.SCOOP_TAP_GITHUB_TOKEN }}"
        homepage: "https://github.com/dbtedman/scrutinise"
        description: "Tool to scrutinise website development security."
        license: "MIT"
        folder: "bucket"

dockers:
    - image_templates:
          - 'dbtedman/scrutinise:{{ .Tag }}-amd64'
      dockerfile: "goreleaser.Dockerfile"
      use: "buildx"
      build_flag_templates:
          - "--pull"
          - "--label=org.opencontainers.image.title=scrutinise"
          - "--label=org.opencontainers.image.description=Tool to scrutinise website development security."
          - "--label=org.opencontainers.image.licenses=MIT"
          - "--label=org.opencontainers.image.created={{.Date}}"
          - "--label=org.opencontainers.image.name={{.ProjectName}}"
          - "--label=org.opencontainers.image.revision={{.FullCommit}}"
          - "--label=org.opencontainers.image.version={{.Version}}"
          - "--label=org.opencontainers.image.source={{.GitURL}}"
          - "--label=org.opencontainers.image.url={{.GitURL}}"
          - "--platform=linux/amd64"
    - image_templates:
          - 'dbtedman/scrutinise:{{ .Tag }}-arm64'
      dockerfile: "goreleaser.Dockerfile"
      use: "buildx"
      build_flag_templates:
          - "--pull"
          - "--label=org.opencontainers.image.title=scrutinise"
          - "--label=org.opencontainers.image.description=Tool to scrutinise website development security."
          - "--label=org.opencontainers.image.licenses=MIT"
          - "--label=org.opencontainers.image.created={{.Date}}"
          - "--label=org.opencontainers.image.name={{.ProjectName}}"
          - "--label=org.opencontainers.image.revision={{.FullCommit}}"
          - "--label=org.opencontainers.image.version={{.Version}}"
          - "--label=org.opencontainers.image.source={{.GitURL}}"
          - "--label=org.opencontainers.image.url={{.GitURL}}"
          - "--platform=linux/arm64"
      goarch: "arm64"

docker_manifests:
    - name_template: 'dbtedman/scrutinise:{{ .Tag }}'
      image_templates:
          - 'dbtedman/scrutinise:{{ .Tag }}-amd64'
          - 'dbtedman/scrutinise:{{ .Tag }}-arm64'
    - name_template: 'dbtedman/scrutinise:latest'
      image_templates:
          - 'dbtedman/scrutinise:{{ .Tag }}-amd64'
          - 'dbtedman/scrutinise:{{ .Tag }}-arm64'
