before:
    hooks:
        - "go mod tidy"

builds:
    -   env:
            - "CGO_ENABLED=0"
        mod_timestamp: "{{ .CommitTimestamp }}"
        flags:
            - "-trimpath"
        goos:
            - "linux"
            - "darwin"
        goarch:
            - "amd64"
            - "arm64"
        main: "./main.go"

archives:
    -   format: "binary"
        name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

release:
    draft: true

changelog:
    skip: true

brews:
    - name: "scrutinise"
      tap:
          owner: "dbtedman"
          name: "homebrew-tap"
          branch: "main"
      homepage: "https://github.com/dbtedman/scrutinise"
      description: "Tool to scrutinise website development security."
      license: "MIT"
