name: "ci"

on:
    pull_request:
        branches:
            - "main"
    push:
        branches:
            - "main"

permissions: "read-all"

jobs:
    linux:
        runs-on: "ubuntu-latest"

        steps:
            -   name: "Checkout Code"
                uses: "actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab"
            -   name: "Setup Go"
                uses: "actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753"
                with:
                    go-version-file: "./go.mod"
            -   name: "Setup golangci-lint"
                uses: "golangci/golangci-lint-action@5f1fec7010f6ae3b84ea4f7b2129beb8639b564f"
                with:
                    version: "latest"
            -   name: "Lint"
                run: "make lint"
            -   name: "Test"
                run: "make test"
            -   name: "Build"
                uses: "goreleaser/goreleaser-action@f82d6c1c344bcacabba2c841718984797f664a6b"
                with:
                    version: "latest"
                    args: "build --clean --snapshot"

    macos:
        runs-on: "macos-latest"

        steps:
            -   name: "Checkout Code"
                uses: "actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab"
            -   name: "Setup Go"
                uses: "actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753"
                with:
                    go-version-file: "./go.mod"
            -   name: "Test"
                run: "make test"
