name: "ci"

on:
    pull_request:
        branches:
            - "main"
    push:
        branches:
            - "main"

permissions: "read-all"

jobs:
    linux:
        runs-on: "ubuntu-latest"

        steps:
            -   name: "Checkout Code"
                uses: "actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9"
            -   name: "Setup Go"
                uses: "actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753"
                with:
                    go-version-file: "./go.mod"
            -   name: "Setup golangci-lint"
                uses: "golangci/golangci-lint-action@08e2f20817b15149a52b5b3ebe7de50aff2ba8c5"
                with:
                    version: "latest"
            -   name: "Lint"
                run: "make lint"
            -   name: "Test"
                run: "make test"
            -   name: "Build"
                uses: "goreleaser/goreleaser-action@f82d6c1c344bcacabba2c841718984797f664a6b"
                with:
                    version: "latest"
                    args: "build --clean --snapshot"

    macos:
        runs-on: "macos-latest"

        steps:
            -   name: "Checkout Code"
                uses: "actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9"
            -   name: "Setup Go"
                uses: "actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753"
                with:
                    go-version-file: "./go.mod"
            -   name: "Test"
                run: "make test"
