name: "ci"

on:
    pull_request:
        branches:
            - "main"
    push:
        branches:
            - "main"

permissions: "read-all"

jobs:
    ci:
        runs-on: "ubuntu-latest"

        steps:
            -   uses: "actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab"
            -   uses: "actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9"
                with:
                    go-version-file: "./go.mod"
            -   uses: "golangci/golangci-lint-action@08e2f20817b15149a52b5b3ebe7de50aff2ba8c5"
                with:
                    version: "latest"
            -   run: "golangci-lint run --verbose"
            -   uses: "goreleaser/goreleaser-action@f82d6c1c344bcacabba2c841718984797f664a6b"
                with:
                    version: "latest"
                    args: "build --clean --snapshot"
