name: "sast"

on:
    pull_request:
        branches:
            - "main"
    push:
        branches:
            - "main"
    schedule:
        -   cron: "0 0 8 * *"

permissions: "read-all"

jobs:
    codeql:
        runs-on: "ubuntu-latest"
        permissions:
            actions: "read"
            contents: "read"
            security-events: "write"
        steps:
            -   name: "Checkout Code"
                uses: "actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab"
            -   name: "Setup CodeQL"
                uses: "github/codeql-action/init@0225834cc549ee0ca93cb085b92954821a145866"
                with:
                    languages: "go"
            -   name: "Setup Go"
                uses: "actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753"
                with:
                    go-version-file: "./go.mod"
            -   name: "Install Go Dependencies"
                run: "make install"
            -   name: "CodeQL Analyze"
                uses: "github/codeql-action/analyze@0225834cc549ee0ca93cb085b92954821a145866"

    ossf:
        runs-on: "ubuntu-latest"
        # ossf scorecard only supported on main branch
        if: github.event_name != 'pull_request'
        permissions:
            security-events: "write"
            id-token: "write"
            contents: "read"
            actions: "read"
        steps:
            -   name: "Checkout Code"
                uses: "actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab"
                with:
                    persist-credentials: false
            -   name: "OpenSSF Scorecard"
                uses: "ossf/scorecard-action@80e868c13c90f172d68d1f4501dee99e2479f7af"
                with:
                    results_file: "results.sarif"
                    results_format: "sarif"
                    publish_results: true
            -   uses: "actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce"
                with:
                    name: "SARIF file"
                    path: "results.sarif"
                    retention-days: 5
            -   name: "Upload Sarif"
                uses: "github/codeql-action/upload-sarif@0225834cc549ee0ca93cb085b92954821a145866"
                with:
                    sarif_file: "results.sarif"

    osv:
        runs-on: "ubuntu-latest"
        permissions:
            contents: "read"
        steps:
            -   name: "Checkout Code"
                uses: "actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab"
            -   name: "Setup Go"
                uses: "actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753"
                with:
                    go-version-file: "./go.mod"
            -   name: "Install OSV Scanner"
                run: |
                    curl -o /usr/local/bin/osv-scanner https://github.com/google/osv-scanner/releases/download/v1.3.2/osv-scanner_1.3.2_linux_amd64 \
                      && chmod +x /usr/local/bin/osv-scanner \
                      && /usr/local/bin/osv-scanner -version
            -   name: "Run OSV Scanner"
                run: "osv-scanner ./"

    snyk:
        permissions:
            contents: "read"
            security-events: "write"
        runs-on: "ubuntu-latest"
        steps:
            -   name: "Checkout Code"
                uses: "actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab"
            -   name: "Setup Go"
                uses: "actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753"
                with:
                    go-version-file: "./go.mod"
            -   name: "Setup Snyk"
                uses: "snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb"
            -   name: "Install Go Dependencies"
                run: "make install"
            -   name: "Snyk Test"
                run: "snyk test --all-projects --detection-depth=1 --sarif-file-output=snyk.sarif"
                continue-on-error: true
                env:
                    SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
            -   name: "Upload Sarif"
                uses: "github/codeql-action/upload-sarif@0225834cc549ee0ca93cb085b92954821a145866"
                with:
                    sarif_file: "snyk.sarif"
