name: "sast"

on:
    pull_request:
        branches:
            - "main"
    push:
        branches:
            - "main"
    schedule:
        -   cron: "0 0 8 * *"

permissions: "read-all"

jobs:
    codeql:
        runs-on: "ubuntu-latest"
        permissions:
            actions: "read"
            contents: "read"
            security-events: "write"
        steps:
            -   name: "Checkout Code"
                uses: "actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab"
            -   name: "Setup CodeQL"
                uses: "github/codeql-action/init@29b1f65c5e92e24fe6b6647da1eaabe529cec70f"
                with:
                    languages: "go"
            -   name: "Setup Go"
                uses: "actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9"
                with:
                    go-version-file: "./go.mod"
            -   name: "Install Go Dependencies"
                run: "make install"
            -   name: "CodeQL Analyze"
                uses: "github/codeql-action/analyze@29b1f65c5e92e24fe6b6647da1eaabe529cec70f"

    osv:
        runs-on: "ubuntu-latest"
        permissions:
            contents: "read"
        steps:
            -   name: "Checkout Code"
                uses: "actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab"
            -   name: "Setup Go"
                uses: "actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9"
                with:
                    go-version-file: "./go.mod"
            -   name: "Install OSV Scanner"
                run: |
                    curl -o /usr/local/bin/osv-scanner https://github.com/google/osv-scanner/releases/download/v1.3.2/osv-scanner_1.3.2_linux_amd64 \
                      && chmod +x /usr/local/bin/osv-scanner \
                      && /usr/local/bin/osv-scanner -version
            -   name: "Run OSV Scanner"
                run: "osv-scanner ./"
